vio_abuse = ["violence", "abuse", "brutality", "harassment", "child_abuse", "mistreatment", "such_violence", "physical_violence", "beatings", "violent_behavior", "violent_acts", "vigilantism", "sexual_abuse", "assaults", "lawlessness", "domestic_violence", "criminal_behavior", "criminality", "sexual_violence", "coercion", "police_brutality", "torture", "bullying", "intimidation", "abuses", "crime", "street_crime", "racial_hatred", "racial_prejudice", "rape", "gang_violence", "physical_abuse", "drug_use", "pedophilia", "crimes", "such_acts", "sexual_activity", "drug_abuse", "abusers", "bigotry", "cruelty", "criminal_activity", "unrest", "intolerance", "misbehavior", "victimization", "atrocities", "sexual_assault", "domestic_abuse", "repression", "such_crimes", "human_rights_violations", "drug_dealing", "criminal_acts", "street_violence", "gang_activity", "bloodshed", "human_rights_abuses", "violent_crime", "drunkenness", "killings", "vandalism", "such_attacks", "such_abuses", "kidnappings", "random_violence", "hate_crimes", "perpetrators", "recent_incidents", "injustices", "mayhem", "disturbances", "political_violence", "police_action", "homophobia", "violent_attacks", "prosecutions", "ostracism", "retribution", "viciousness", "sex_crimes", "drug_addiction", "gun_violence", "thievery", "mental_illness", "drug_trade", "truancy", "terror", "misdeeds", "other_abuses", "false_accusations", "oppression", "massacres", "molestation", "incitement", "other_crime", "criminal_justice_system", "mass_murder", "genocide", "extremism"]


abuse = ["abuse", "child_abuse", "sexual_abuse", "physical_abuse", "harassment", "mistreatment", "abuses", "misbehavior", "misconduct", "sexual_assault", "abusers", "domestic_violence", "misdeeds", "molestation", "sexual_misconduct", "neglect", "maltreatment", "inappropriate_behavior", "criminal_behavior", "sex_crimes", "sexual_harassment", "coercion", "abused", "domestic_abuse", "sex_abuse", "incompetence", "criminality", "rape", "pedophilia", "violent_behavior", "mental_illness", "beatings", "false_accusations", "child_neglect", "malfeasance", "misuse", "abuse_cases", "torture", "bullying", "physical_violence", "prosecutions", "drug_abuse", "other_abuses", "brutality", "police_misconduct", "crimes", "drug_use", "criminal_activity", "rape_victims", "worst_cases", "such_crimes", "sexual_violence", "hazing", "abusive_priests", "such_abuse", "delinquency", "sexual_activity", "alcohol_abuse", "physical_harm", "graft", "criminal_acts", "such_abuses", "psychiatric_problems", "criminal_justice_system", "police_abuse", "dishonesty", "child_abuse_cases", "emotional_problems", "seizures", "substance_abuse", "assaults", "racial_prejudice", "many_victims", "racial_bias", "cheating", "abusing", "sexual_activities", "truancy", "criminal_offenses", "corporal_punishment", "criminal_conduct", "adultery", "sexual_assaults", "sexual_contact", "pedophiles", "family_violence", "punishments", "cruelty", "drunkenness", "date_rape", "child_welfare_officials", "sexual_conduct", "police_brutality", "drug_addiction", "spousal_abuse", "unfairness", "culpability"]


violence = ["violence", "bloodshed", "such_violence", "unrest", "lawlessness", "street_violence", "brutality", "mayhem", "more_violence", "racial_hatred", "disturbances", "violent_attacks", "such_attacks", "violent_acts", "terror", "bloodletting", "political_violence", "extremism", "intolerance", "vigilantism", "kidnappings", "street_crime", "confrontations", "repression", "gang_violence", "militancy", "rebellion", "ethnic_hatred", "intimidation", "incitement", "random_violence", "hatred", "suicide_bombings", "ethnic_cleansing", "rioting", "further_violence", "assassinations", "assaults", "black_townships", "recent_violence", "bigotry", "violent_protests", "police_action", "hate", "crime", "civil_disobedience", "riots", "uprising", "police_brutality", "physical_violence", "provocation", "insurgency", "strife", "oppression", "civil_unrest", "security_forces", "killings", "massacres", "drug_trade", "insurrection", "clashes", "aggression", "rising_violence", "rebellions", "mass_murder", "extremists", "police_violence", "extremist_groups", "militias", "suicide_attacks", "carnage", "mass_arrests", "anarchy", "armed_conflict", "Islamic_militants", "ethnic_tensions", "ethnic_conflict", "racial_tensions", "racial_violence", "such_acts", "fundamentalists", "Islamic_fundamentalism", "uprisings", "gangs", "racial_tension", "crime_wave", "violent", "other_attacks", "intifada", "street_protests", "victimization", "looting", "hostage-taking", "beatings", "atrocities", "mob_violence", "violent_confrontations", "hysteria", "terrorist_acts", "violent_behavior"]


def diff(first, second):
    second = set(second)
    return [item for item in first if item not in second]

vio_only = diff(vio_abuse, abuse)
diff(vio_only, violence)

# ['human_rights_violations', 'drug_dealing', 'gang_activity', 'human_rights_abuses', 'violent_crime', 'vandalism', 'hate_crimes', 'perpetrators', 'recent_incidents', 'injustices', 'homophobia', 'ostracism', 'retribution', 'viciousness', 'gun_violence', 'thievery', 'other_crime', 'genocide']

